name: Go

on:
  push:
    branches: [ "main", "premain", "dev" ]

jobs:
  check-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        large_files: ["test/", "prev_test/", "base_waves/"]
    steps:
      - uses: actions/checkout@v4

      - name: Check that large files not exist
        run: |
          if [ -f "${{ matrix.large_files }}" ]; then
            echo "File '${{ matrix.large_files }}' exists!"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'

    - name: Set up output dirs
      run: make clearTestDir

    - name: Test
      run: go test -test.short -v ./... -bench=^$ -tags 'NoBenchmarks'
